apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-changestream-producer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/parkyoungjin-888/k8s-deployment.git
    targetRevision: main
    path: manifests/kafka-changestream-producer
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
