namespace: default

image: img234/kafka-consumer-parquet:0.1.0

port: 8000

appId: "kafka-consumer-parquet-001"

replicaCount: 0

nodeType: "server"

resources:
  limits:
    cpu: "500m"
    memory: "1024Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"

serviceType: ClusterIP
