apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    namespace: {{ .Values.namespace }}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - yj-t8-plus
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      namespace: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        namespace: {{ .Values.namespace }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image }}"
          ports:
            - containerPort: {{ $.Values.port }}
          env:
            - name: CONFIG_HOST
              value: "grpc-config-fetcher"
            - name: CONFIG_PORT
              value: "21001"
            - name: APP_ID
              value: "{{ $.Values.appId }}"
            - name: TZ
              value: Asia/Seoul
          securityContext:
            privileged: true
          volumeMounts:
            - name: video-device
              mountPath: /dev/video0
          resources: {{- toYaml $.Values.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: video-device
          hostPath:
            path: /dev/video0
            type: CharDevice
